{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clamav-rest.fullname" . }}
  labels:
    {{- include "clamav-rest.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "clamav-rest.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - protocol: TCP
          port: http
      {{- with .Values.networkPolicy.ingressFrom }}from: {{ toYaml . | nindent 8 }}{{ end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              {{- include "clamav-rest.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: clamav
      ports:
        - protocol: TCP
          port: {{ .Values.clamav.service.port }}
    - ports:
        - protocol: TCP
          port: 443
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
  {{- end }}
{{- end }}
